/** @format */

// ** Next
import Head from 'next/head';

// Pages
import EmploymentForm from 'src/pages/employmentForm';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<EmploymentForm />
			</main>
		</>
	);
}
